package jetbrains.mps.lang.generator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a3a0a74b0be = new IconResource("mappingConf.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a05b0be = new IconResource("generatorScript.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a08b0be = new IconResource("templateFragment.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a19b0be = new IconResource("switch.png", IconContainer.class);
}
